name: "Update known checksums"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Run every day at 4am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"
      - name: Update known checksums
        id: update-known-checksums
        run:
          node dist/update-known-checksums/index.js
          src/download/checksum/known-checksums.ts ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci --ignore-scripts && npm run all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "chore: update known checksums"
          title:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          body:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          base: main
          labels: "automated-pr,update-known-checksums"
          branch: update-known-checksums-pr
          delete-branch: true
