name: "Update known checksums"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Run every day at 4am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "20"
      - name: Update known checksums
        id: update-known-checksums
        run:
          node dist/update-known-checksums/index.js
          src/download/checksum/known-checksums.ts ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci --ignore-scripts && npm run all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore: update known checksums"
          title:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          body:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          base: main
          labels: "automated-pr,update-known-checksums"
          branch: update-known-checksums-pr
          delete-branch: true
